### ISSUE TITLE
Copy & paste not possible in editor?

### ISSUE THREAD

**Issue by Maddoc42** [FauDroids/MrHyde#15]
Possibly due to long clicks being handled in the UI and not being forwarded to other parties.

**Comment by s1hofmann** [comment]
Copy & paste is possible by doubletapping a word. Not very intuitive, but it's possible 🙆

**Comment by Maddoc42** [comment]
Ah darn, you are right! And long clicks seems to work now as well to start selection mode, hm ... Can't reproduce this for now, maybe it only happens in certain situations?
