### ISSUE TITLE
Add support for BitBucket

### ISSUE THREAD

**Issue by mdeabreu** [FauDroids/MrHyde#18]
Add the ability to connect to a (possibly private) repo on BitBucket. Or expand the scope and add support for arbitrary hosts (ssh or https).

**Comment by ohaz** [comment]
Would probably not be that much work on the server side. On the client side it would be kind of a big deal though.
On the other hand it would be a really nice feature to support more than just github. We will definitely think and talk about it. I hope we'll have the time to work on it.

**Comment by CRamsan** [comment]
I would suggest to add support for local repos. I use other git clients to clone from github/bitbucket and my private repos, so if I could just load an existing repo then I would have access to any Jekyll site regardless of where it lives.

**Comment by Maddoc42** [comment]
Bitbucket support is coming as part of the upcoming release. Checkout https://play.google.com/apps/testing/org.faudroids.mrhyde for a preview.
