### ISSUE TITLE
Don't close login dialog when switching between apps

### ISSUE THREAD

**Issue by foosel** [FauDroids/MrHyde#19]
I have two factor authentication setup for my Github account. The authenticator is installed on the same device I've MrHyde installed on. Which leads to the rather unfortunate situation that I can't login:

1. In MrHyde click the login button, Github's login form is displayed
2. Enter username and password in the dialog and submit the form
3. Github's dialog to enter the key from the authenticator is displayed.
4. Switch to authenticator and copy current (very short lived) key
5. Return to MrHyde. Dialog pop-up has vanished, back to 1. 

Repeat ad infinitum.

**Comment by ohaz** [comment]
Thank you for reporting, we'll look into it :+1:

**Comment by Maddoc42** [comment]
Just released a new version to the PlayStore, let us know if that solves your problem!

**Comment by foosel** [comment]
Will do, not seeing the update yet, will keep you in the loop and report back as soon as I can.

Big thanks for the fast response! :+1:

**Comment by foosel** [comment]
Works great, thanks again.

**Comment by ohaz** [comment]
Awesome. Good work @Maddoc42 :+1:
