### ISSUE TITLE
Unable to commit (no gh-pages branch support)

### ISSUE THREAD

**Issue by Haroenv** [FauDroids/MrHyde#31]
![](http://i.imgur.com/bGBSIgj.png)

**Comment by Maddoc42** [comment]
Can you provide some more information (e.g. what were you trying to do, what was the git diff)? Also, are you working on your phone + computer in parallel?

**Comment by Haroenv** [comment]
I have worked on my computer before, and was now testing out to post on my phone too. The git diff was a new post created in the project root.

**Comment by Maddoc42** [comment]
Hm, having trouble reproducing the issue. Could you reset the repo on your phone (menu top right, "Discard changes"), stop the app, and then walk me through the steps you are taking to get to this issue?

Also, in case it is public, which repo did are you experiencing this issue with? Are you using the master branch?

**Comment by Haroenv** [comment]
I’m using the `gh-pages` branch of haroen.me/trip <http://haroen.me/trip>. 

I’m doing: 

1. go to the repo
2. add new post
3. commit

I then see that error.

Thanks

**Comment by Haroenv** [comment]
Weird thing I noticed. The date is a month in advance when creating a post.

![](http://imgur.com/bkJ0Qrx)

**Comment by Maddoc42** [comment]
Ah, MrHyde does currently not support branches other than heads/master, sorry. And because your repo "only" has the gh-pages you get the 404 error. I'll try adding branch support in the next couple of days if there is some free time. Thanks for pointing that out!

Regarding the wrong post time, what's the file name of the post? (see all files --> _posts)

**Comment by Haroenv** [comment]
Thanks for your reply. If you could add that before monday that would be super cool and really streamline my process (no need to go to the desktop github site, the only real alternative I found).

The name of the post is correct (2015-09-01-Title.md)

**Comment by Maddoc42** [comment]
See #29
