### ISSUE TITLE
Ignore `site.baseurl` during site preview

### ISSUE THREAD

**Issue by Haroenv** [FauDroids/MrHyde#34]
This makes links and CSS not work when you use that (ie for me `baseurl` is `/trip`)

**Comment by Maddoc42** [comment]
Nice catch!

Implementing this should be as simple as appending a ```--baseurl``` to the Jekyll serve command on the preview server. @ohaz @s1hofmann any thoughts on this?

**Comment by ohaz** [comment]
--baseurl is a serve argument, we just use the build command.
We could patch the config file. That would be kind of a messy solution but should work. Any other ideas?

**Comment by Haroenv** [comment]
You will also need to point the server to `ip:4000/baseurl/` instead of `ip:4000`

**Comment by ohaz** [comment]
Can you test if it works now? I hope 25b5fcf327a38763a504c7206866edd2af16764e fixes the issue

**Comment by Haroenv** [comment]
Weirdly, I have no idea how to compile an android app from source, you could fork github.com/haroenv/trip and try it, that repository uses `baseurl` or explain to me how I'd compile it?

**Comment by ohaz** [comment]
No need to compile the android app :) Works with the current version of the android app.

I have forked your repo and tested it, it looks fine to me now. Can you just give it a try (just use the app you have installed at the moment and click on preview again) and tell me if everything works as expected?

**Comment by Haroenv** [comment]
Yep, works perfectly now! Thanks

**Comment by ohaz** [comment]
:+1: Nice. Have fun!
