### ISSUE TITLE
Filled in favourite icon

### ISSUE THREAD

**Issue by Haroenv** [FauDroids/MrHyde#35]
It would be cleaner to me if the heart was filled in.

![](http://i.imgur.com/WRKTNye.png)

**Comment by Maddoc42** [comment]
That's really a matter of taste. Originally we had the heart filled out, but then decided against it (too much red in the "fav repos" tab). If you want you could create a mockup screenshot with the heart filled in and then we can vote on this.

**Comment by Haroenv** [comment]
![](http://i.imgur.com/pPdMeU2.png?1) 

Worst mockup ever, but I think it is more intuitive that a filled in icon means "yes". I think it wouldn't be too busy since you often have a lot more non-favourite than favourite repositories.

YMMV

**Comment by Maddoc42** [comment]
Hm, looks good actually :smile: will play around with that once a release is coming up.

**Comment by Maddoc42** [comment]
Part of the upcoming release. Checkout https://play.google.com/apps/testing/org.faudroids.mrhyde

**Comment by Maddoc42** [comment]
Released as v1.0.0.
