### ISSUE TITLE
Feature request: Recurse over posts subdirectories

### ISSUE THREAD

**Issue by jacobmischka** [FauDroids/MrHyde#38]
A relatively common theme is to separate posts into folders by year and even month. MrHyde says you have no published posts if all of the posts are in `_posts/2015`.

**Comment by Maddoc42** [comment]
Thanks for the feedback, that makes sense.

According to this http://jekyllrb.com/docs/frontmatter/ subdirectories are called categories. Does placing posts in there change anything regarding the regular post naming conventions? For example is this correct?

```
_posts/
  2015/
    04/
      2015-04-01-some-post.md
```

... or rather ...

```
_posts/
  2015/
    04/
      01-some-post.md
```

**Comment by jacobmischka** [comment]
As far as I know, they're called categories if they're in directories after the site is compiled, but I'm not sure about before. It doesn't affect naming, your first option is correct.

**Comment by Maddoc42** [comment]
I just added your suggestion via [v0.3.7](https://github.com/FauDroids/MrHyde/tree/v0.3.7), its going through the playstore now. Let us know how that works for you.

**Comment by jacobmischka** [comment]
Wow that's much faster than I would have expected, thanks! It's a little buggy for me for some reason on my nexus 5x with marshmallow. ![](http://i.imgur.com/huPDTjx.jpg)

**Comment by jacobmischka** [comment]
Oh actually that's probably just because of the title length and has nothing to do with this addition. That's something different entirely then, never mind! Thanks for the quick addition!

**Comment by Maddoc42** [comment]
Yes, that something different (unfortunately? :smile:). But thanks for pointing it out anyways!
