### ISSUE TITLE
'require' cannot load "jekyll-sitemap"

### ISSUE THREAD

**Issue by mattymaloney** [FauDroids/MrHyde#40]
When requesting a preview, the process ends with the "Getting Jekyll Output" screen. The third bullet point in the list states `'require': cannot load such file -- jekyll-sitemap (LoadError)`.

**Comment by s1hofmann** [comment]
Looks like our preview server was missing the jekyll-sitemap gem. I just installed the necessary files, could you try again and let us know if your problem is resolved?

**Comment by mattymaloney** [comment]
Yes! That works. Thank you.
