### ISSUE TITLE
Make uppercase and lowercase the same in All Repositories list

### ISSUE THREAD

**Issue by aviaryan** [FauDroids/MrHyde#43]
Currently the order of repos in my All Repositories list is something like - 
```
aviaryan/ABC
aviaryan/JKL
aviaryan/def
```
It would be better if caps don't matter.

**Comment by Maddoc42** [comment]
True, thanks for catching that. Should be pretty straight forward to fix.

**Comment by Maddoc42** [comment]
Now also part of the upcoming release! :rocket:

**Comment by Maddoc42** [comment]
Released as v1.0.0.
