### ISSUE TITLE
Add markdown cheatsheet 

### ISSUE THREAD

**Issue by davrandom** [FauDroids/MrHyde#44]
(Hi, thanks for the great app!)

It would be nice to have a short markdown cheatsheet quickly available from the options menu.
And maybe the possibility to add the hint directly in the post by clicking on it.

e.g. image hint
`![text](imagelocation)`

**Comment by Maddoc42** [comment]
Hey @davrandom, thanks for the feedback.

Cheatsheet sounds great. At some point we thought about having some sort of auto completion (effort?),   cheatsheet definitely sounds more doable at the moment.

Any thoughts on how this might look visually? I'm thinking a separate "page" or maybe small overlay that pops up when clicking on a button, and then the option to select an entry?

**Comment by davrandom** [comment]
Hi !
I was thinking about something like this:

![screenshot_2016-07-18-14-40-36](https://cloud.githubusercontent.com/assets/5477436/16916724/490ebe14-4cf6-11e6-947d-a73a670bb5d9.png)

When editing a post, you click on the top right corner, the "options" menu

![screenshot_2016-07-18-14-40-39](https://cloud.githubusercontent.com/assets/5477436/16916738/5ef5b57a-4cf6-11e6-8f61-bddd62db09b6.png)

and there you have a markdown option. The markdown can be a different page with few examples. If you click on an example it adds the pseudo code where you had the cursor blinking.

**Comment by Maddoc42** [comment]
Yes, that would work! Alternatively we could have some kind of overlay pop up from the bottom (triggered through the top menu like you mentioned or maybe swipe up??).

If you are interested in an PR feel free, as we are more focusing on integrating other Git services into MrHyde for the moment :)

**Comment by s1hofmann** [comment]
@davrandom I started implementing your feature request today, so better Markdown handling is coming to MrHyde! :+1:

**Comment by davrandom** [comment]
Cool! 
I have no idea how to code for Android, never tried... maybe this could be a good time to start getting my hands on it.

Thanks for all the feedback and comments;)

**Comment by davrandom** [comment]
How long does it take normally to propagate until google play?

**Comment by s1hofmann** [comment]
We just pushed the update, so it should be available soon™.

**Comment by davrandom** [comment]
it's there! wonderful! thanks!
