### ISSUE TITLE
Migrate from  GitHub API to a regular Git client

### ISSUE THREAD

**Issue by Maddoc42** [FauDroids/MrHyde#45]
MrHyde currently uses the GitHub API for fetching, writing and committing files. While this allows clients to not (!) download a whole repository and still being able to create changes, it comes with some disadvantages:

- No git workflow: there is no explicit "pull" to get new files. As such local changes files which have not been committed can possible overwrite newer versions on GitHub.
- Support for other Git providers difficult: the way files are being pulled from GitHub and committed back is 100% specific to GitHub. Other providers, such as BitBucket or even local repositories cannot be supported without implementing a custom integration with them. (#18, #42)
- Complex: a lot less can go wrong when working with local files, as compared to working with remote ones.

This issue will track the progress of migrating MrHyde from using the GitHub API for dealing with files, to using a regular Git client that supports basic Git operations, such as pull, push, commit etc.

Work in progress: https://github.com/FauDroids/MrHyde/tree/github-api-to-git-migration

Steps involved:

- [x] cloning remote GitHub repositories
- [x] viewing files / directories
- [x] creating / editing / saving regular files
- [x] creating / editing / saving drafts and posts
- [x] creating commits
- [x] pushing
- [x] pulling
- [x] switching branches (#29)
- [x] rendering previews
- [x] store clone repositories meta data in local DB
- [x] UI for showing and adding cloned repositories

:rocket:

**Comment by Maddoc42** [comment]
Woooho! That took longer than expected, but we are getting close :rocket: :rocket: current preview available as a beta on the [PlayStore](https://play.google.com/apps/testing/org.faudroids.mrhyde).

I'll give the beta a couple of days for testing and collecting feedback before going live. Any thoughts appreciated! :octocat:

**Comment by Haroenv** [comment]
Cooool 😎😎😎

**Comment by Maddoc42** [comment]
Released as v1.0.0.
