### ISSUE TITLE
Cannot upload images.

### ISSUE THREAD

**Issue by clarkhacks** [FauDroids/MrHyde#46]
All i get is an error.

**Comment by Maddoc42** [comment]
Thanks for reporting this issue.

You are probably referring to uploading an image from the file explorer? What device model do you have? Where is the image stored? What app is being opened as a picker?

Also, any chance you can get your hands on a stacktrace?

**Comment by clarkhacks** [comment]
I'm using a Samsung Galaxy Core Prime. Mr.Hyde opens my gallery for the
image selector. I can tap on the image I wish to upload and it goes to the
Mr. Hyde screen where I can rename the image and press upload upon pressing
upload I get this screen (the attached image)

**Comment by Maddoc42** [comment]
Missing screenshot?

**Comment by clarkhacks** [comment]
Sorry about that. I had some upload issues! Here is the image.

![screenshot](http://i.imgur.com/cphpirz.png)

**Comment by Maddoc42** [comment]
Great, awesome!

Seems like MrHyde is missing the read external storage permission. That's a pretty straight forward fix. Funny how that never happend before when choosing images from the Google Photos App.

**Comment by clarkhacks** [comment]
Thanks so much @Maddoc42 for looking into it! It means a lot as I love the Mr.Hyde app and use it a lot.

**Comment by Maddoc42** [comment]
@clarkhacks if you care to test this, I have included a fix in the upcoming release. Beta version of this app is available at https://play.google.com/apps/testing/org.faudroids.mrhyde

**Comment by clarkhacks** [comment]
It works beautifully love the new design features.

**Comment by Maddoc42** [comment]
Cheers, thanks for testing! :+1:

**Comment by Maddoc42** [comment]
Released as v1.0.0.
