### ISSUE TITLE
Feature request: Preview in Browser

### ISSUE THREAD

**Issue by holbue** [FauDroids/MrHyde#49]
Please add a button to the "preview" toolbar, which can open the preview in external browsers.

Would be very useful for testing, e.g. MrHydes internal browser lags of options like 'desktop view'.

**Comment by Maddoc42** [comment]
Fair point :+1:

It might even make sense at this point to replace all native Android WebViews with Chrome Custom Tabs (https://developer.chrome.com/multidevice/android/customtabs), similar to what happens on Twitter / Slack when you open a link.

Reasons to migrate :sunny:
- Users can see the URL they are visiting + SSL details.
- Menu for sharing link + opening in browser.
- Chrome Custom tabs support "pre loading" of URLs in various forms, might speedup loading the login pages.

Reasons not to migrate :zap:
- On the preview page users see the URL of the preview right away. This might be confusing as it suggest that MrHyde is hosting the preview permanently somewhere, which is not the case.

Thoughts?

**Comment by Haroenv** [comment]
You could add a toast or popup the first time it's opened making clear that it's temporary

**Comment by Maddoc42** [comment]
Makes sense. Some kind of help text / hint is needed here.

**Comment by Maddoc42** [comment]
Released with v1.0.1. :muscle: 

Implementation uses the regular Android WebView like before. Reasons for not migrating were:

- Too little styling options: action bar color can be configured, but not the text color :see_no_evil: 
- GitHub / Bitbucket login WebViews cannot be migrated: MrHyde depends on the callback URL containing an access code. With Chrome custom tabs this URL can not longer be intercepted.
- Yet another dependency: I wouldn't really have minded, but given the above limitations it seems to much.

Anyways, you can now open the preview in your regular browser :tada:
