### ISSUE TITLE
"Preview in Browser" not working

### ISSUE THREAD

**Issue by thermoskanne** [FauDroids/MrHyde#50]
When I click the new Menu to open the Preview in external Browser, the Browser opens, but my Jekyll Page ist not loading. I only see this message forever:

![screenshot_20161016-161716](https://cloud.githubusercontent.com/assets/10990447/19418090/194d827e-93bd-11e6-9bb4-6d159b8d7715.png)

I'm using latest Chrome.

**Comment by Maddoc42** [comment]
@thermoskanne thanks for reporting this. Could you answer a couple of additional questions?

- Are you getting the same behavior in the MrHyde app?
- How large is your repository? Could you paste a link to it here?

Pulling in @s1hofmann and @ohaz, they are the experts on this :male_detective: :muscle:

**Comment by ohaz** [comment]
When it's just saying "Initializing", that means that the javascript is not loading/running. Does your browser support javascript? Or is it disabled by a plugin / setting?

**Comment by Maddoc42** [comment]
@ohaz what happens if the repository is really large or the preview server does not return any status update, would the JS output be the same?

**Comment by ohaz** [comment]
[main.dart](https://github.com/FauDroids/MrHyde/blob/master/server/redirector_source/web/main.dart#L13) instantly sets the output to "Getting Jekyll Output" as soon as the javascript is finished loading. It's independent of anything server related.

**Comment by Maddoc42** [comment]
@thermoskanne could you try opening the preview link in a different browser? I don't see how regular Chrome on Android should pose any problems, so let's make sure this is really a browser issue.

**Comment by thermoskanne** [comment]
@Maddoc42 

- In MrHyde's internal preview, everythings is loaded & shown correctly.
- Sry, my repo is private, but it's pretty small (1.9 MB incl. images)
- Is use Android for Chrome, without extensions, but I'm on a custom ROM ("Tesla", Android 6.0.1)
- Javascripts are not blocked. I don't experience any problems with any other website at all.
- I also tried Firefox for Android (here I have some Addons, but none should influence MrHyde) with exactly the same output: "Initalizing" forever.
- I'm not sure, if this should work at all, but if I open the URL which MrHyde sents me to in Desktop Browsers, I also got the same issue.

Might the problem be, that I have my repo on gitlab, which is pretty new for MrHyde?

**Comment by Maddoc42** [comment]
Just to confirm: how much time passed between you starting the preview and you making that screenshot?

Previews are deleted from the server every couple of minutes, but the error message should be different though ...

**Comment by thermoskanne** [comment]
After I previewed in MrHyde, I tried it in Chrome and Firefox on Android, then I mailed the URL to my Desktop. 7min maybe?

I just tried it again with around ~1.5min  between Preview in MrHyde loaded and opening the Link on my Desktop (this time with Chromium):

![mrhydepollerinchromium](https://cloud.githubusercontent.com/assets/10990447/19420248/89254f1c-93e7-11e6-93e5-41008fb59fd4.png)

**Comment by ohaz** [comment]
I was able to take a look at the build you were running. Apparently, the whole /packages/ folder is going missing.
My guess is that we delete all subfolders before copying the results of the jekyll process to the output folder. This means that as soon as the build is done, the poller webpage will stop working. We've probably done this to prevent pages that use the /packages/ folder themselves from breaking. I'll have a deeper look at it tomorrow!

**Comment by Maddoc42** [comment]
Great discovery @ohaz 👍 

There seem two be two issues here:

- Hitting the poller.html URL once the preview has been rendered doesn't work, as it's dependencies will have been deleted. Solution might be to have a separate static poller site, which receives the preview ID as a query parameter.
- "Open in Browser" on the client will always open the poller.html site. Besides breaking for the reasons above, it would also better to open the current page in the browser, not the starting page. 

I'll have a look at that client issue ... :space_invader:

**Comment by Maddoc42** [comment]
@thermoskanne just released v1.0.2 with a small fix that might help. Let us know if that works for you! :dancing_women:

**Comment by thermoskanne** [comment]
@Maddoc42 That fixed it for me! Thanks! :)

**Comment by Maddoc42** [comment]
@thermoskanne sweet :tada:

@ohaz: close or update backend as well?

**Comment by ohaz** [comment]
Now that I think of hit, having a seperate static poller site should've been the way to do it the first time. This is a fix that should be done. Getting query parameters in javascript apparently isn't that hard ([stackoverflow](http://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript)), so it should be possible. Would require a lot of work on the server though.

**Comment by Maddoc42** [comment]
Alright :+1: let's see how the client fix solves this in the long term. For now changing the backend doesn't seem worth the effort. Closing :wave:
