### ISSUE TITLE
Feature request: Spanish translation

### ISSUE THREAD

**Issue by Include-Poetry** [FauDroids/MrHyde#54]
Hi.
I really love this app, and therefore would like to work doing the spanish translation of the application and its description in the PlayStore. I just need to know which files to modify. And the same for the description that is currently published. Thanks in advance.

**Comment by Maddoc42** [comment]
Wow, that's awesome!! :muscle:

For the app all strings that need to be translated are in the [strings.xml](https://github.com/FauDroids/MrHyde/blob/master/client/app/src/main/res/values/strings.xml). You might not need a translation for all entries (for example H1 stays H1), just leave those out. Once finished the new `strings.xml` file goes in a new directory called `values-es`. From there Android should take care to do the actual language switching. :space_invader:

We don't yet have a place where the Playstore description is saved here. I'll work on that.

@ohaz @s1hofmann what about localization on the backend? Do we want / need this? @Include-Poetry would that be important to you?

@Include-Poetry are these enough guidelines to get you started? Again, your effort is much appreciated! :clap:

**Comment by Haroenv** [comment]
Is there a style guid on how to translate git-related things? I just took a look to translate it into Dutch, but I'm not sure to leave them in English, or translate them literally "cloning", "repository" ...

**Comment by Maddoc42** [comment]
Hm, good question. Any idea what GitHub etc. are doing?

**Comment by ohaz** [comment]
The only thing really worth localising on the backend would probably be the jekyll output - however we can't localise that, that's the job of the jekyll guys. Other than that, the only server output that clients ever see is the output of poller.html and main.dart in "/server/redirector_source/web/"

**Comment by Haroenv** [comment]
Github has no localisations.

**Comment by Maddoc42** [comment]
@Haroenv then my guess is to leave those as they are in English. As a rough guideline: everything that relates to commands of git or other programs (clone, checkout, stash, ...) can be considered technical terms that don't need localization. Does that makes sens?

**Comment by Haroenv** [comment]
Sure, that's what I would prefer most myself.

**Comment by Include-Poetry** [comment]
I'm done with the translation, however, in spanish accents are used, should I write them in HTML code as `&aacute;` or add the line `<?xml version="1.0" encoding="utf-8"?>` or neither?

**Comment by Maddoc42** [comment]
Adding the `utf-8` declaration should be fine 👍
