### ISSUE TITLE
Move repository clone directory to public storage

### ISSUE THREAD

**Issue by Maddoc42** [FauDroids/MrHyde#59]
Right now MrHyde clones repositories to the private file storage of the app (see [here](https://github.com/FauDroids/MrHyde/blob/master/client/app/src/main/java/org/faudroids/mrhyde/git/RepositoryFactory.java#L39) for example). Seeing that git credentials are stored separately, should we move the clone location to the public external storage of the device?

Yes, we should! :muscle: 
- Makes integration with other apps possible

No, never! :speak_no_evil: 
- Private git repositories become available to all apps on the device, security concerns?

Thoughts anyone?

Thanks @sarah11918 for bringing this up! :+1:

**Comment by sarah11918** [comment]
Thanks for opening the issue! My initial intent was to be able to use *any* Android markdown editor to edit posts/pages, then save those files to where ever the repository exists locally to then push to Gitlab. Thinking about it some more, this would also help add things like images for posts to the repository.

The app is currently working really well for making small, text changes to existing pages and posts. In fact, if I notice a typo on a page, it's actually easier to use this app to correct it than to pull out my laptop.

But if I want to create a post from scratch in a more featured markdown editor, attach an image perhaps... then certainly having the repositories available to other apps is a big convenience.

(My personal goal is to see whether I can run a Jekyll blog entirely from a Chrome OS/Android set up, so I'm really curious about the possibilities that moving the clone location opens up.)  :)

**Comment by dynobo** [comment]
Please move to public storage, at a custom folder.
I often need to use more advanced editors for more complicated edits. Currently I use root to set the permissons for the repo folder, but this is really a pain...

Regarding security: Its not a big topic for me here. But if you want to improve it a little, add some visual feedback on what was changed in a commit (which files, amount of changes)

**Comment by Maddoc42** [comment]
Released as of version 1.1.0 :rocket:

MrHyde creates a new directory under the root SD folder (where that is depends on what android device you are using :see_no_evil:) called `MrHyde`. In there you have one directory for each git provider (GitHub, BitBucket, GitLab), and then the repositories sorted by owner name.

You can also directly open a file from within MrHyde, by either long clicking on it, or choosing the "Share" menu item from the text editor.

For these changes to take effect you will have to delete any cloned repositories in MrHyde, and then re-clone them.

@sarah11918 @dynobo let me know if this works for you! :blush:
