### ISSUE TITLE
Repos in public android folder not working

### ISSUE THREAD

**Issue by dynobo** [FauDroids/MrHyde#64]
Hi,

After the last release, which allows storage of the [cloned repo in a public folder,](https://github.com/FauDroids/MrHyde/issues/59) I deleted my local repo and re-added it. No luck: the repo still gets cloned to /data/data/... subfolder. Also complete uninstall, reinstall with deleting app cache + settings didn't help.

I'm using MrHyde 1.1.0 and my repo is on gitlab.com

**Comment by Maddoc42** [comment]
Hey, thanks for reporting this. Could you answer a couple more questions?

- What device are you using?
- Does your device have an external SD card? Did you install MrHyde on that SD card?
- Do you have other apps on your device that put files (everything but photos, music, videos, contacts) in a public directory?
- What is the path to your public directory on your path?

**Comment by dynobo** [comment]
What device are you using?
* Moto G first generation

Does your device have an external SD card? 
* No

Do you have other apps on your device that put files (everything but photos, music, videos, contacts) in a public directory?
* E.g. Messengers like Threema & WhatsApp create their own folders with various files. "Notify & Fitness for Mi Band" stores also data in pub dir

- What is the path to your public directory on your path?
* Root of my pub dir is: /storage/emulated/0/

Hope this helps :)

Philipp Eichhorn <notifications@github.com> schrieb am 16.11.2016:
>Hey, thanks for reporting this. Could you answer a couple more
>questions?
>
>- What device are you using?
>- Does your device have an external SD card? Did you install MrHyde on
>that SD card?
>- Do you have other apps on your device that put files (everything but
>photos, music, videos, contacts) in a public directory?
>- What is the path to your public directory on your path?

**Comment by sarah11918** [comment]
Same issue here:

What device are you using?
*Samsung Galaxy Note 4

Does your device have an external SD card? Did you install MrHyde on that SD card?
*Yes, external card. No, MrHyde is installed on the device.

Do you have other apps on your device that put files (everything but photos, music, videos, contacts) in a public directory?
* Yes, I do have a few apps that have created folders directly in /storage/emulated/0/
(I think that's what you're asking)

What is the path to your public directory on your path?
* Root of my pub dir is: /storage/emulated/0/

**Comment by sarah11918** [comment]
Hey, just wondering if we're any closer on this. I have two different Android devices and can't find the local repository on my device via a file manager app in either of them. 

(My first generation Note 10 tablet is pretty old, running 4.1.2, and I'm just glad the app works, to be honest.  :)  But I figured that maybe finding the files on that device would help me figure out where I can access them on my Note 4, but no luck. I don't seem to have access to these files, or a MrHyde folder, anywhere on either device.

I'll be switching to a Chromebook soon, and would really like to figure out how to put new markdown files composed in an editor like JotterPad into my local repository so I can then push to Gitlab.

Thanks for any help!

**Comment by Maddoc42** [comment]
Time goes by too quickly :see_no_evil: 

@sarah11918 @dynobo are you guys by any chances using repos hosted on GitLab / Bitbucket? If so great news! Only the GitHub repos were being store in a public directory, the others were not. I just released version 1.1.1 to the playstore, should be available in a couple of hours :smile:

**Comment by sarah11918** [comment]
\o/

Why yes, I'm using GitLab. So with any luck, that should work for me.  :)

I'll test it this weekend and let you know. Thanks again so much!

**Comment by dynobo** [comment]
Yes, I also used GitLab! Thanks for the fix!!! :-)

**Comment by sarah11918** [comment]
W00t! I can see my GitLab directory with my file explorer. I owe you some of this good Canadian whisky I'm sipping right now.  🥃

**Comment by Maddoc42** [comment]
Yeah, sweet :smile: thank you for you patients you two, glad this is finally working :rocket:
